### PR TITLE
Ga and As pottentials

### PR DESCRIPTION
**Pull request by setten**

### CODE REVIEW

**Comment by setten** [comment]
?

--
Université catholique de Louvain
SST/IMCN - Institute of Condensed Matter and Nanosciences (IMCN)

Dr. Michiel J. van Setten

NAPS - Chemin des Étoiles 8 bte L7.03.01
1348 Louvain-la-Neuve (Belgium)
Email: michiel.vansetten@uclouvain.be mjvansetten@gmail.com
Telefon: +32 10 478681
--

2016-09-03 12:59 GMT+02:00 gmatteo <notifications@github.com>:

**Comment by gmatteo** [comment]
I looked at Ga-d and Ad-d with one projector because I'm discussing with Yannick about the new calculations. The logder for d of Ga-d-single and As-d-single starts to deviated from the AE already around 0. I played a bit with the parameters but I was not able to improve the situation.
I think we have to use the previous version of Ga-d and As-d with two projectors.

BTW- I've just realized that Ga-d is still using the old model core charge.
I will have to regenerate the pseudo

**Comment by setten** [comment]
I saw that as well, don’t understand how that one was missed.

**Comment by setten** [comment]
me to, I  also did not manage improve it. However it is the d log der that has that much of a problem. The delta’s are not that bad actually for both singles

cheers

**Pull request merged**
